-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 13:49:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_name` VARCHAR(45) NOT NULL,
  `height` INT NOT NULL,
  `department_id` INT NOT NULL,
  INDEX `fk_Student_Department_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Department`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`Department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `professor_name` VARCHAR(45) NOT NULL,
  `department_id` INT NULL,
  PRIMARY KEY (`professor_id`),
  INDEX `fk_Professor_Department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`Department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `professor_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_Course_Professor1_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `mydb`.`Professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_Course` (
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  INDEX `fk_Student_Course_Student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_Student_Course_Course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Course_Student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Student` (`student_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Course_Course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
